backend:
  name: github
  branch: feature/gatsby5-migration
  repo: fntechgit/fnEvent
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend:
  url: http://localhost:8081/api/v1

media_folder: static/img
public_folder: /img

collections:
  - name: "configurations"
    label: "Configurations"
    editor:
      preview: false
    files:
      - file: "src/content/site-settings/index.json"
        label: "Site Settings"
        name: "site-settings"
        fields:
          - {label: "Favicons", name: favicons, widget: object, fields: [
              {label: "Favicon 180x180", name: favicon180, widget: image},
              {label: "Favicon 32x32", name: favicon32, widget: image},
              {label: "Favicon 16x16", name: favicon16, widget: image}
            ]}
          - {label: "Widgets", name: widgets, widget: object, fields: [
              {label: "Chat", name: chat, widget: object, fields: [
                {label: "Show QA", name: showQA, widget: boolean, required: false, default: false},
                {label: "Show Help", name: showHelp, widget: boolean, required: false, default: false},
                {label: "Default Filter Criteria", name: defaultScope, widget: select, required: false, default: 'page', options: [
                  {label: "In this Room", value: "page" },
                  {label: "All Attendees", value: "show" }
                ]}
              ]},
              {label: "Schedule", name: schedule, widget: object, fields: [
                {label: "Allow Clickable Behavior", name: allowClick, widget: boolean, required: false, default: true},
              ]}
            ]}
      - file: "src/content/ads.json"
        label: "Advertisement"
        name: "ads"
        fields:
          - {label: "Ads", name: "ads", widget: list, fields: [
              {label: "Page", name: "section", widget: string},
              {label: "Ads", name: "columnAds", widget: list, required: false, fields: [
                {label: "Image", name: "image", widget: object, required: false, fields: [
                  {label: "File", name: "file", widget: image, required: false, default: ''},
                  {label: "Alt", name: "alt", widget: string, required: false, default: ''},
                ]},
                {label: "Button", name: "button", widget: object, required: false, fields: [
                  {label: "Text", name: "text", widget: string, required: false},
                  {label: "Link", name: "link", widget: string, required: false}
                ]},
                {label: "Column", name: "column", widget: select, options: [
                  {label: "Left", value: "left" },
                  {label: "Center", value: "center" },
                  {label: "Right", value: "right" },
                ]},
                {label: "Specific Event?", name: "eventId", widget: string, required: false, default: 0}
              ]},
            ]}
      - file: "src/content/sponsors-tiers.json"
        label: "Sponsors Tiers"
        name: "sponsors-tiers"
        fields:
          - {label: "Tiers", name: "tiers", widget: list, fields: [
              {label: "Tier", name: "name", widget: string},
              {label: "Widget Title", name: "widgetTitle", widget: string, required: false},
              {label: "ID", name: "id", widget: ncw-id, prefix: tier, hidden: true},
              {label: "Badge", name: "badge", widget: object, required: false, fields: [
                {label: "File", name: "file", widget: image, required: false, default: ''},
                {label: "Alt", name: "alt", widget: string, required: false, default: ''},
              ]},
              {label: "Lobby", name: "lobby", widget: object, fields: [
                {label: "Lobby Template", name: "lobbyTemplate", widget: select, required: false, default: 'small-images', options: [
                  {label: "Big Images", value: "big-images" },
                  {label: "Small Images", value: "small-images" },
                  {label: "Horizontal Images", value: "horizontal-images" },
                  {label: "Carousel", value: "carousel" },
                ]},
                {label: "Display", name: display, widget: boolean, required: false, default: false}
              ]},
              {label: "Expo Hall Page", name: "expoHallPage", widget: object, fields: [
                {label: "Expo Hall Template", name: "expoHallTemplate", widget: select, required: false, default: 'medium-images', options: [
                  {label: "Big Images", value: "big-images" },
                  {label: "Medium Images", value: "medium-images" },
                  {label: "Small Images", value: "small-images" },
                ]},
                {label: "Display", name: display, widget: boolean, required: false, default: false}
              ]},
              {label: "Sponsor Page", name: "sponsorPage", widget: object, fields: [
                {label: "Sponsor Page Template", name: "sponsorTemplate", widget: select, required: false, default: 'small-header', options: [
                  {label: "Big Header", value: "big-header" },
                  {label: "Small Header", value: "small-header" },
                ]},
                {label: "Widgets", name: "widgets", widget: object, fields: [
                  {label: "Disqus", name: disqus, widget: boolean, required: false, default: false},
                  {label: "Live Event", name: liveEvent, widget: boolean, required: false, default: false},
                  {label: "Schedule", name: schedule, widget: boolean, required: false, default: false},
                  {label: "Banner", name: banner, widget: boolean, required: false, default: false}
                ]}
              ]},
              {label: "In Event Template", name: "eventTemplate", widget: select, required: false, default: 'small-images', options: [
                {label: "Big Images", value: "big-images" },
                {label: "Small Images", value: "small-images" },
                {label: "Horizontal Images", value: "horizontal-images" },
              ]},
            ]}
          - {label: "Expo Hall Header Image", name: "imageHeader", widget: object, required: false, fields: [
              {label: "File", name: "file", widget: image, default: '', required: false},
              {label: "Alt", name: "alt", widget: string, required: false}
            ]}
          - {label: "Lobby Button", name: lobbyButton, widget: object, fields: [
              {label: "Text", name: "text", widget: string, required: false, default: ''},
              {label: "Link", name: "link", widget: string, required: false, default: ''}
            ]}
      - file: "src/content/navbar.json"
        label: "Navbar"
        name: "navbar"
        fields:
          - {label: "Navbar", name: "items", widget: list, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Link", name: "link", widget: string},
              {label: "Display?", name: "display", widget: boolean, required: false},
              {label: "Requires Auth?", name: "requiresAuth", widget: boolean, required: false, default: false},
              {label: "Show only at Show Time?", name: "showOnlyAtShowTime", widget: boolean, required: false, default: false},
              {label: "Show only on page", name: "pageRestriction", widget: select, multiple: true, default: ["ANY"], options: ["ANY", "MARKETING", "LOBBY", "ACTIVITY", "SHOW", "CUSTOM_PAGE"]},
            ]}
      - file: "src/content/footer.json"
        label: "Footer"
        name: "footer"
        fields:
          - {label: "Columns", name: "columns", widget: list, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Display", name: "display", widget: boolean, required: false},
              {label: "Items", name: "items", widget: list, fields: [
                {label: "Title", name: "title", widget: string},
                {label: "Link", name: "link", widget: string},         
              ]}
            ]}
          - {label: "Logo", name: "logo", widget: object, fields: [
              {label: "Display", name: "display", widget: boolean, required: false},
            ]}
          - {label: "Social", name: "social", widget: object, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Display", name: "display", widget: boolean, required: false},
              {label: "Networks", name: "networks", widget: list, fields: [
                {label: "Icon", name: "icon", widget: string},
                {label: "Link", name: "link", widget: string},
                {label: "Display", name: "display", widget: boolean, required: false},
              ]}
            ]}
          - {label: "Legal", name: "legal", widget: list, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Link", name: "link", widget: string},         
            ]}
      - file: "src/content/posters-pages.json"
        label: "Posters Pages"
        name: "posters-pages"
        fields:
          - {label: "Posters Pages", name: "postersPages", widget: list, fields: [
              {label: "Name", name: "name", widget: string, required: false},
              {label: "Track Group Id", name: "trackGroupId", widget: number},
              {label: "Title", name: "title", widget: string },
              {label: "Subtitle", name: "subtitle", widget: string },
              {label: "Background Image", name: "image", widget: image, required: false},
            ]}
  - name: "home"
    label: "Lobby Site"
    editor:
      preview: false
    files:
      - file: "src/content/home-settings.json"
        name: "home-settings"
        label: "Lobby Settings"
        fields:
          - {label: "Center Column", name: "centerColumn", widget: object, fields: [
              {label: "Speakers", name: "speakers", widget: object, fields: [
                {label: "Show Today Speakers", name: "showTodaySpeakers", widget: boolean, required: false},
                {label: "Show Feature Speakers", name: "showFeatureSpeakers", widget: boolean, required: false}
              ]}
            ]}
          - {label: "Home Hero", name: homeHero, widget: object, fields: [
              {label: "Title", name: title, widget: string},
              {label: "Sub Title", name: subTitle, widget: string, required: false},
              {label: "Image", name: "image", widget: object, required: false, fields: [
                {label: "File", name: "file", widget: image, default: '', required: false},
                {label: "Alt", name: "alt", widget: string, required: false},
              ]},
              {label: "Copy", name: copy, widget: text, required: false}
            ]}
          - {label: "Featured Event - Live Event Widget", name: live_now_featured_event_id, widget: number, required: false, default: null}
  - name: "marketing"
    label: "Marketing Site"
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        name: "marketing-site"
        label: "Marketing Site"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "marketing-page"}
          - {label: "Hero Banner", name: "heroBanner", widget: "object", fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Subtitle", name: "subtitle", widget: string, required: false},
              {label: "Date", name: "date", widget: string, required: false},
              {label: "Date Layout", name: "dateLayout", widget: boolean, required: false},
              {label: "Time", name: "time", widget: string, required: false},
              {label: "Buttons", name: "buttons", widget: object, fields: [
                {label: "Register Button", name: "registerButton", widget: object, fields: [
                  {label: "Text", name: "text", widget: string},
                  {label: "Display", name: "display", widget: boolean, required: false},
                ]},
                {label: "Login Button", name: "loginButton", widget: object, fields: [
                  {label: "Text", name: "text", widget: string},
                  {label: "Display", name: "display", widget: boolean, required: false},
                ]}
              ]},
              {label: "Background Image", name: "background", widget: object, required: false, fields: [
                {label: "Image", name: "image", widget: image, required: false},
                {label: "Alt", name: "alt", widget: string, required: false},
              ]},
              {label: "Images", name: "images", widget: list, fields: [
                {label: "Image", name: "image", widget: image, required: false},
                {label: "Alt", name: "alt", widget: string, required: false},
              ]},
            ]}
  - name: "pages"
    label: "Pages"
    folder: "src/pages/custom-pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "custom-page"}
      - {label: Title, name: title, widget: string}
      - {label: "User Requirement", name: userRequirement, widget: select, options: ["NONE", "LOGGED_IN", "HAS_TICKET"], default: "NONE"}
      - {label: "Body", name: body, widget: markdown}
  - name: "sponsors"
    label: "Sponsors Data"
    editor:
      preview: false
    files:
      - file: "src/content/sponsors.json"
        label: "Tier Sponsors"
        name: "tier-sponsors"
        fields:
          - {label: "Tier Sponsors", name: "tierSponsors", widget: list, summary: "{{tier[0].label}}", fields: [
              {label: "Tier", name: "tier", widget: ncw-file-relation, collection: configurations, file: sponsorsTiers, target_field: tiers, id_field: id, display_fields: name},
              {label: "Sponsors", name: "sponsors", widget: list, fields: [
                {label: "Name", name: "name", widget: string },
                {label: "External ID", name: "id", widget: number },
                {label: "Sponsor ID", name: "sponsorId", widget: number, required: false},
                {label: "Company ID", name: "companyId", widget: number, required: false},
                {label: "Featured Event ID", name: "featuredEventId", widget: number, required: false},
                {label: "Title", name: "title", widget: string, required: false},
                {label: "Intro", name: "intro", widget: markdown, required: false},
                {label: "Contact Email", name: "email", widget: string, required: false},
                {label: "Live Video Chat Link", name: "chatLink", widget: string, required: false},
                {label: "Marquee Text", name: "marquee", widget: string, required: false},
                {label: "Sponsor Color", name: "sponsorColor", widget: string, required: false},
                {label: "Logo", name: "logo", widget: object, required: false, fields: [
                  { label: "File", name: "file", widget: image, default: '', required: false },
                  { label: "Alt", name: "alt", widget: string, required: false },
                ]},
                {label: "Advertise Image", name: "advertiseImage", widget: object, required: false, fields: [
                  { label: "File", name: "file", widget: image, default: '', required: false },
                  { label: "Alt", name: "alt", widget: string, required: false },
                ]},
                {label: "External Link", name: "externalLink", widget: string, required: false},
                {label: "Social Networks", name: "socialNetworks", widget: list, fields: [
                  {label: "Icon", name: "icon", widget: string},
                  {label: "Link", name: "link", widget: string},
                  {label: "Display", name: "display", widget: boolean, required: false},
                ]},
                {label: "Documents", name: "documents", widget: object, fields: [
                  {label: "Slides", name: "slides", widget: list, fields: [
                    {label: "Class Name", name: class_name, widget: hidden, default: "PresentationSlide"},
                    {label: "Name", name: name, widget: string},
                    {label: "Order", name: order, widget: number},
                    {label: "Link", name: link, widget: file, default: "/documents/" }
                  ]},
                  {label: "Links", name: "links", widget: list, fields: [
                    {label: "Class Name", name: class_name, widget: hidden, default: "PresentationLink"},
                    {label: "Name", name: name, widget: string},
                    {label: "Order", name: order, widget: number},
                    {label: "Link", name: link, widget: string}
                  ]},
                  {label: "Videos", name: "videos", widget: list, fields: [
                    {label: "Class Name", name: class_name, widget: hidden, default: "PresentationVideo"},
                    {label: "Name", name: name, widget: string},
                    {label: "Order", name: order, widget: number},
                    {label: "Link", name: link, widget: string}
                  ]},
                ]},
                {label: "Ads", name: "columnAds", widget: list, required: false, fields: [
                  {label: "Image", name: "image", widget: image},
                  {label: "Alt", name: "alt", widget: string, required: false},
                  {label: "Button Text", name: "text", widget: string, required: false},
                  {label: "Link", name: "link", widget: string, required: false}
                ]},
                {label: "Uses Sponsor Page?", name: "usesSponsorPage", widget: boolean, required: false},
                {label: "Header Image", name: "headerImage", widget: object, required: false, fields: [
                  { label: "File", name: "file", widget: image, default: '', required: false},
                  { label: "Alt", name: "alt", widget: string, required: false},
                ]},
                {label: "Mobile Header Image", name: "headerImageMobile", widget: object, required: false, fields: [
                  { label: "File", name: "file", widget: image, default: '', required: false},
                  { label: "Alt", name: "alt", widget: string, required: false},
                ] },
                {label: "Side Image", name: "sideImage", widget: object, required: false, fields: [
                  { label: "File", name: "file", widget: image, default: '', required: false},
                  { label: "Alt", name: "alt", widget: string, required: false},
                ]},
                {label: "Video Header", name: "headerVideo", widget: string, required: false},
                {label: "Show Logo in Event Page", name: "showLogoInEventPage", widget: boolean, required: false, default: true},
              ]}
            ]}
